### ISSUE TITLE
Game Crashes during load

### ISSUE THREAD

**Issue by dabomb6405** [infernalexp/Mining-Master#1]
Whenever I try to load minecraft with the newest version (1.1.1), my game crashes, it says something about failed infernal expansion mixins, even though I don't have IE installed. Here's the log.
[latest.log](https://github.com/infernalexp/Mining-Master/files/7369875/latest.log)

**Comment by Afrocntrik** [comment]
I get the same error, crashes at startup with no crash log either
[latest.log](https://github.com/infernalexp/Mining-Master/files/7370347/latest.log)
