### ISSUE TITLE
[bug and suggestion 1.16.5] MiningMaster ore malachite - bug effect

### ISSUE THREAD

**Issue by MrJorman** [infernalexp/Mining-Master#10]
the Air Malachite crystal, if it is combined with pants in the blacksmith's table to the maximum level, then a triple jump will appear, but if you take off your pants, then the jump magically remains.

https://youtu.be/I6ueTCnTbVU

This effect does not disappear if I take off my pants, if I die, if I heal, if I re-visit the server - nothing helps, help)
And you can stretch this effect somehow, if I use a cloud in a bank from the Artifacts mod, and then the first jump is ignored by the mod) For example, if I have an Artifacts mod and a cloud in a bank from it, then I will end up with 4 jumps = instead of 3.
https://www.curseforge.com/minecraft/mc-mods/artifacts

**Comment by Dariensg** [comment]
Please follow the new issue format so that I am sure to have all necessary information!

**Comment by Dariensg** [comment]
Fixed by b5b7ffe61011a387df3ec43e847c8ef1cdaf9227
