### ISSUE TITLE
[bug 1.16.5] MiningMaster Auto-Smelt effect

### ISSUE THREAD

**Issue by MrJorman** [infernalexp/Mining-Master#13]
If someone does a spell melting on a pickaxe, what happens is some kind of bug after a while that all players with their bare hands can melt what they break. Sand - glass, wood - coal.

My server crashed for some reason, look for a crash theme.

**Comment by Dariensg** [comment]
Please follow the new issue format so that I am sure to have all necessary information!

**Comment by Dariensg** [comment]
Could not reproduce.
