### ISSUE TITLE
A small mistake in zh_cn.json

### ISSUE THREAD

**Issue by Kasualix** [infernalexp/Mining-Master#14]
Sorry I did not check it carefully.

https://github.com/infernalexp/Mining-Master/blob/main/src/main/resources/assets/miningmaster/lang/zh_cn.json

Line 3,  "block.miningmaster.ice_sapphire_ore": "寒冰冰蓝宝石矿石", it should be   "block.miningmaster.ice_sapphire_ore": "寒冰蓝宝石矿石".

There is a redundant character “冰”.

**Comment by Dariensg** [comment]
That's completely fine! Would you be able to PR a fix for that? I'd be happy to merge it in for you!

**Comment by Kasualix** [comment]
OK I did that, thank you.
