### ISSUE TITLE
Valid recipes do not include damaged tools in the Gem Forge recipe book

### ISSUE THREAD

**Issue by nekomaster1000** [infernalexp/Mining-Master#19]
### Describe the Bug

When using the Gem Forge, the recipe book will not recognised tools with any wear as a valid component in a Supra or Ultima tool recipe. This is not a problem with non-damaged tools. (On commit 1548aaf2c05d92d2bdd7fe7d4c798e4d270959f1)

### Reproduction Steps

1. Place down a Gem Forge.
2. Acquire a Diamond tool and enough gems to create a Supra tool.
3. Notice how the recipe book will not suggest a valid recipe despite being able to create it manually.

### Expected Result

The Gem Forge recipe book should recognise tools and armour as valid components even if they're damaged.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/47757977/160912048-523323e5-a07d-40b0-80ac-ac2c66344a24.png)

### Operating System

Windows 10

### Mod Version

2.1.0

### Minecraft Version

1.16.5

### Forge Version

36.2.26

### Other Mods

JEI, Tetra.

### Additional Context

"Probably an NBT issue." - Hellion

**Comment by SwanX1** [comment]
kinda sounds like a skill issue

**Comment by nekomaster1000** [comment]
> kinda sounds like a skill issue

I was so tempted to write that myself LOL
Also thank you for the email notification Github very cool 👍

**Comment by Dariensg** [comment]
I think this is unfortunately a quirk of just how the Recipe Book works and I'm not sure I'm going to be able to change it.
