### ISSUE TITLE
[2.1.0] [1.16.5] Crashing on server startup

### ISSUE THREAD

**Issue by Thresh90** [infernalexp/Mining-Master#21]
### Describe the Bug

Was trying to run this this mod solo after many attempts of trying to get it working with a pack i have setup, decided to run it on its own and it crashes

provided crash log:
https://pastebin.com/1pLsnvcv

### Reproduction Steps

1.run the mod on forge's server version 36.2.34 on its own
2.crashes, even without other mods along with it.
3.
...

### Expected Result

crash

### Operating System

Windows 10

### Mod Version

2.1.0

### Minecraft Version

1.16.5

### Forge Version

36.2.34

**Comment by SkullDiamond** [comment]
I got the same issue but whit the 3.0.0 version 
crash: https://pastebin.com/eNtngNnK
