### ISSUE TITLE
Bug (1.18) - Nether ores have incorrect sounds

### ISSUE THREAD

**Issue by Bonniethebunny-hub** [infernalexp/Mining-Master#23]
### Describe the Bug

The nether based ores (Heart Rhodonite, Power Pyrite and Kinetic opal), have basic stone sounds, in contrast to other nether ores like nether quartz.

### Reproduction Steps

1.Mining ore (be the mining master)

### Expected Result

Hear stone

### Operating System

Windows 10

### Mod Version

2.1.0

### Minecraft Version

1.16.5

### Forge Version

111

**Comment by Dariensg** [comment]
Fixed by #24
