### ISSUE TITLE
has failed to load correctly

### ISSUE THREAD

**Issue by krjencik** [infernalexp/Mining-Master#29]
### Describe the Bug

Minecraft wont run

### Reproduction Steps

1.download forge 41.0.98
2. download this mod
3. run Minecraft
...

### Expected Result

see the Minecraft's main menu

### Operating System

windows 10

### Mod Version

2.1.0

### Minecraft Version

1.16.5

### Forge Version

41.0.98

### Additional Context

Minecraft version is 1.19, not 1.16.5
and Mod version is 3.0.5 and not 2.1.0

**Comment by SwanX1** [comment]
MM is currently incompatible with Forge 41.0.64+

**Comment by krjencik** [comment]
aha... ty. so i wont need to upload a log file?

**Comment by SwanX1** [comment]
> aha... ty. so i wont need to upload a log file? 

It would have been helpful if I didn't know what to look for, please, next time provide a log and/or crash report right off the bat.

**Comment by krjencik** [comment]
sorry i was trying to do it...
