### ISSUE TITLE
Mining Master failed to load correctly

### ISSUE THREAD

**Issue by ErikProgram87** [infernalexp/Mining-Master#32]
[latest.log](https://paste.gg/aa2c03ffcc974c2f95f76aaae512315e) 
[crash-2022-08-14_11.47.29-fml.txt](https://paste.gg/9395248b43cb4ba29567ef610dc4622e) 

I don't know where and how to report this, so here are the files.

**Comment by SwanX1** [comment]
Mining Master is not yet compatible with Forge 41.0.64+
This issue has been fixed in development, see commit 2cc97d7091d412d3bb7794591c6598d11d25c182
