### ISSUE TITLE
[1.19.1] Config file not generated?

### ISSUE THREAD

**Issue by TheHandwovenBox** [infernalexp/Mining-Master#35]
### Describe the Bug

I've noticed that upon launching the game with the mod installed, no config file was generated in the config folder.

### Reproduction Steps

1. Isolated Mining Master in the mods folder
2. Launched Minecraft Forge
3. Saw no config file generated in the config folder

### Expected Result

A config file being generated for editing

### Operating System

Windows 10

### Mod Version

2.1.0

### Minecraft Version

1.16.5

### Forge Version

42.0.9

**Comment by Dariensg** [comment]
There is no config in 1.19. All configurable stuff was moved to datapacks in 1.19 and can be configured by a custom datapack. This is the new way of doing things with Forge, as generation modification is handled by BiomeModifiers that are in datapacks.

**Comment by TheHandwovenBox** [comment]
Pardon me for asking, but where can I find/make said datapack? I saw no file in the datapack folder for my world, and I cannot seem to find any of the ores ingame. I've never tinkered with datapacks, so I apologize for my ignorance.

**Comment by Dariensg** [comment]
You're totally fine! Never really messed with datapacks myself, but I can give you some resources. First, [this](https://minecraft.fandom.com/wiki/Data_pack#Contents) gives a quick outline of the format of how to make a datapack. I've linked to the specific "Contents" section, but more on that page may be useful to you. As far as Mining Master specific stuff goes, datapacks are built into mods, hence why there's nothing in your datapack folder. You can still override existing datapacks with a custom one, however. [Here](https://github.com/infernalstudios/Mining-Master/tree/1.19/src/main/resources/data) is a link to the Mining Master datapack information so you can take a look through and see what you want to tweak. The Mining Master gems are very rare ingame, which is probably why you haven't encountered any. Hope these resources help! If you have any further questions, I'd be happy to help them in our discord, [here](https://discord.com/invite/UYGSn94).
