### ISSUE TITLE
Incorrect tags

### ISSUE THREAD

**Issue by JaisDK** [infernalexp/Mining-Master#36]
### Describe the Addition

You're not tagging things correctly

https://github.com/infernalstudios/Mining-Master/tree/1.19/src/main/resources/data/forge
should be
https://github.com/infernalstudios/Mining-Master/tree/1.19/src/main/resources/data/forge/tags

**Comment by Dariensg** [comment]
Good catch! Sorry about that! Must've made those in a hurry and just missed that extra directory. I'll get that fixed up in the next version!
