### ISSUE TITLE
Bug Freeze Enchant.

### ISSUE THREAD

**Issue by GitJhopa** [infernalexp/Mining-Master#44]
### Describe the Bug

In the Mining master there is a Freeze enchantment, if you kill a player with this enchantment, then after respawning it remains with him forever! 

### Reproduction Steps

1. Enchant random sword Freeze Enchant
2. Kill other player
3. Infinity Freezes in player.
...

### Expected Result

Upon death, the player should not have a residual freeze effect

### Operating System

Windows 10

### Mod Version

3.0.7

### Minecraft Version

1.19.2

### Forge Version

1.19.2-43.2.14

**Comment by Dariensg** [comment]
Does this only happen when killing with a Freezing sword? I've just tested with a Freezing bow and it did not occur.

**Comment by GitJhopa** [comment]
Yes, I checked the sword. I don't know about the axe and stuff.

**Comment by Dariensg** [comment]
I'm curious about a bow or if it's just the sword.

**Comment by GitJhopa** [comment]
> I'm curious about a bow or if it's just the sword.

wait bro, i give you video.

**Comment by GitJhopa** [comment]
https://youtu.be/UminQ4VFdqY

**Comment by Dariensg** [comment]
This seems to be client/server desync. I'll work to fix this within about a week.
