### ISSUE TITLE
The heartfealt enchantment is completely broken.

### ISSUE THREAD

**Issue by GitJhopa** [infernalexp/Mining-Master#45]
### Describe the Bug

I also looked at the code for breaking armor if there is a heartfeal enchantment, the logic is a bit incomprehensible, if I have all the armor enchanted for heartfeal II, then in total it will come out II + II + II + II = 8 and +1 breakage strength, total for 1 hit each piece of armor loses 9 durability. Don't you think it's broken? It seems to me that each individual element of the armor needs to lose II + 1 durability = that is, each element loses 3 armor, and as I understand it, the III durability enchantment does not work with this.

### Reproduction Steps

I also looked at the code for breaking armor if there is a heartfeal enchantment, the logic is a bit incomprehensible, if I have all the armor enchanted for heartfeal II, then in total it will come out II + II + II + II = 8 and +1 breakage strength, total for 1 hit each piece of armor loses 9 durability. Don't you think it's broken? It seems to me that each individual element of the armor needs to lose II + 1 durability = that is, each element loses 3 armor, and as I understand it, the III durability enchantment does not work with this.

### Expected Result

I believe that the heartfealt enchantment should take away durability only considering one piece of armor, that is, if the enchantment is II level, then it is spent for 1 hit = 3 durability. And the enchantment unbreaking I, II, III is also taken into account.

### Operating System

Windows 10

### Mod Version

3.0.7

### Minecraft Version

1.19.2

### Forge Version

1.19.2-43.2.14

**Comment by Dariensg** [comment]
Not sure what you're trying to say here. The way the extra durability damage on Heartfelt works is that whenever you take damage, each heartfelt piece takes extra damage equal to the level of enchantment on that specific piece. So if you're wearing all Heartfelt II armor, each piece takes 3 durability damage.

**Comment by GitJhopa** [comment]
No! Your code is broken! It counts for all armor enchantments, and deals 9 durability damage and does not count for III durability enchantments.

**Comment by GitJhopa** [comment]
Helmet - Heartfelt II
Chestplate - Heartfelt II
Leggings - Heartfelt II
Boots - Heartfelt II

In total, for 1 hit, I lose 9 durability of each armor!
Although it should lose 3 durability of each armor.
Also, the durability III enchantment doesn't work with the Heartfelt enchantment at all.

**Comment by GitJhopa** [comment]
My players are shocked by this, complaining that III durability on armor doesn't work with the Heartfelt enchantment and the armor breaks in seconds, losing 9 durability per hit.
