### ISSUE TITLE
I can't enchant through stones on a thug from the SavageRavage mod

### ISSUE THREAD

**Issue by GitJhopa** [infernalexp/Mining-Master#46]
### Describe the Bug

I can't enchant through stones on a savage_and_ravage:cleaver_of_beheading from the SavageRavage mod https://legacy.curseforge.com/minecraft/mc-mods/savage-and-ravage

None of the stones are compatible with this sword from the mod.

### Reproduction Steps

I can't enchant through stones on a savage_and_ravage:cleaver_of_beheading from the SavageRavage mod https://legacy.curseforge.com/minecraft/mc-mods/savage-and-ravage

None of the stones are compatible with this sword from the mod.

### Expected Result

I want the thug from the Savage Ravage mod to be enchantablet hrough the stones

### Operating System

Windows 10

### Mod Version

3.0.7

### Minecraft Version

1.19.2

### Forge Version

1.19.2-43.2.14

**Comment by Dariensg** [comment]
What gems have you tried? Just looked at their code and compared. Ice Sapphire for Freezing and Spirit Garnet for Leeching should theoretically both work.

**Comment by GitJhopa** [comment]
No stone is suitable. savage_and_ravage:cleaver_of_beheading Doesn't count as a sword.
