### ISSUE TITLE
Duping experience!!!

### ISSUE THREAD

**Issue by GitJhopa** [infernalexp/Mining-Master#49]
### Describe the Bug

https://youtu.be/By6t-LCgEKA see video

### Reproduction Steps

https://youtu.be/By6t-LCgEKA see video

### Expected Result

no duping please.

### Operating System

Windows 10

### Mod Version

3.0.7

### Minecraft Version

1.19.2

### Forge Version

1.19.2-43.2.14

**Comment by Dariensg** [comment]
This bug is fascinating. I've replicated it and figured out why it gives experience when it shouldn't. What I haven't worked out quite yet is why it's happening. I'll keep you updated.
