### ISSUE TITLE
Crash when Equipping Armour [1.19.2]

### ISSUE THREAD

**Issue by Vivid141** [infernalexp/Mining-Master#57]
### Describe the Bug

**Description:** When playing a custom modpack, equipping armour (I've tested with an enchanted golden helmet from a ruined portal so far) causes the game to crash. After that, I cannot re-enter the world as whenever I load in, the armour is still equipped, which causes another crash.

**Important:** The dropdown doesn't let me select a version of Mining Master past release 3.0.7, but I was _actually_ using release 4.1.4 _[Edited the version of Mining Master in the 'Mod Version' section after posting]._ Other mods I believe could be relevant to the crash will be listed in the 'Other Mods' section.

**Log:** https://mclo.gs/oZw8nZ3

### Reproduction Steps

1. Load custom modpack (this is a step as I believe the error may be an incompatibility with other mods I'm using)
2. Enter world
3. Equip a piece of armour (I used an enchanted golden helmet)

### Operating System

Windows 11

### Mod Version

~~3.0.7~~ _4.1.4_

### Minecraft Version

1.19.2

### Forge Version

43.3.0

### Other Mods

My mod list is 101 long, so I'm not going to list all of them- they should be in the crash log given above if necessary- but there are some mods I believe could be part of what caused the crash.

**Versions:**
- Caverns and Chasms: 1.0.0 (Adds natural enchantments to gold and chainmail armour)
- Cold Sweat: 2.3-b02a (Adds insulation attributes to armour)
- Allurement: 3.2.1 (Adds new enchantments and changes the behaviour of some vanilla enchantments)
- The Endergetic Expansion: 4.0.0 (Adds a new armour piece with a double jump ability)
- Enemy Expansion: 2.1.0 (Adds new armour pieces with unique attributes)

It may be the case that a different mod is incompatible and that caused my game to crash, but these are the ones I can logically see as possibly being incompatible with Mining Master.

**Comment by nekomaster1000** [comment]
And your world is accessible again after removing Mining Master?

**Comment by Vivid141** [comment]
Actually, no. I just checked on another world and the crash still occured, my apologies. It must be another mod causing the crash. My bad!
